import React from "react";
import { useBanner } from "../../context/BannerContext";
import { useState,useEffect } from "react";
import './Blog.css'
function Blog() {
  const { setBannerTitle, setBreadcrumb, setBannerImage } = useBanner();

  useEffect(() => {
    setBannerTitle("Blog");
    setBreadcrumb("Blog");
    setBannerImage("/other-banner.png");
  }, []);
  return (<div className="article-wrapper">
      <p className="intro">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
      </p>

      <h2>Lorem ipsum dolor sit amet</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio...
      </p>

      <div className="image-text-row">
        <img src="/blog1.png" alt="Trainer lifting weights" />
        <div className="text-content">
          <h2>Lorem ipsum dolor sit amet</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet...
          </p>
        </div>
      </div>

      <h2>Lorem ipsum dolor sit amet</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum...
      </p>

      <div className="image-text-row">
        <img src="/blog2.png" alt="Trainer at gym" />
        <div className="text-content">
          <h2>Lorem ipsum dolor sit amet</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
          </p>
        </div>
      </div>

      <h2>Conclusion</h2>
      <p>
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer non euismod lorem...
      </p>
    </div>
  );
}

export default Blog;
